
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vital-chi-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=vital_chi_db
      - SUPABASE_PROJECT_REF=${SUPABASE_PROJECT_REF}

  mysql:
    image: mysql:8.0
    container_name: vital-chi-mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=vital_chi_db

volumes:
  mysql-data: